steps:
  - id: 'Rodando docker-compose'
    name: 'gcr.io/$PROJECT_ID/docker-compose'
    args: ['-f', 'docker-compose.prod.yaml', 'up', '-d']

  - id: 'Rodando id'
    name: 'gcr.io/cloud-builders/docker'
    args: ['exec', '-t', 'php', 'id']

  - id: 'Rodando ls'
    name: 'gcr.io/cloud-builders/docker'
    args: ['exec', '-t', 'php', 'ls']

  - id: 'Rodando ls ..'
    name: 'gcr.io/cloud-builders/docker'
    args: ['exec', '-t', 'php', 'ls', './..']

  - id: 'Rodando id www-data'
    name: 'gcr.io/cloud-builders/docker'
    args: ['exec', '-t', '-u', 'www-data', 'php', 'id']

  - id: 'Rodando id root'
    name: 'gcr.io/cloud-builders/docker'
    args: ['exec', '-t', '-u', 'root', 'php', 'id']

  - id: 'Rodando composer'
    name: 'gcr.io/cloud-builders/docker'
    args: ['exec', '-t', 'php', 'composer', 'install']

  - id: 'Copiando .env'
    name: 'gcr.io/cloud-builders/docker'
    args: ['exec', '-t', 'php', 'cp', '.env.example', '.env']

  - id: 'Copiando .env.testing'
    name: 'gcr.io/cloud-builders/docker'
    args: ['exec', '-t', 'php', 'cp', '.env.testing.example', '.env.testing']

  - id: 'Rodando key:generate'
    name: 'gcr.io/cloud-builders/docker'
    args: ['exec', '-t', 'php', 'php', 'artisan', 'key:generate']

  - id: 'Rodando migrations'
    name: 'gcr.io/cloud-builders/docker'
    args: ['exec', '-t', 'php', 'php', 'artisan', 'migrate']

  - id: 'Rodando PhpUnit'
    name: 'gcr.io/cloud-builders/docker'
    args: ['exec', '-t', 'php', 'php', 'vendor/bin/phpunit', '-c', 'phpunit.xml']
