version: '3.4'
services:
  php:
    build:
      context: .docker/php
      target: php
    container_name: php
    entrypoint: dockerize -wait tcp://mysql:3306 -timeout 40s php-fpm
    volumes:
      - .:/var/www/html
      - .docker/php/.user.ini:/usr/local/etc/php/conf.d/user.ini
    depends_on:
      - mysql
      - redis
  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - .:/var/www/html
      - .docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    ports:
      - '80:80'
  redis:
    image: redis:alpine
    container_name: redis
  mysql:
    build: .docker/mysql
    container_name: mysql
    volumes:
      - .docker/mysql/dbdata:/var/lib/mysql
      - .docker/mysql/entrypoint-initdb:/docker-entrypoint-initdb.d
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
