version: '3.4'
services:
  php:
    build:
      context: .docker/php
      target: php
    entrypoint: dockerize -wait tcp://mysql:3306 -timeout 40s .docker/php/entrypoint.sh
    volumes:
      - .:/var/www/html
      - .docker/php/.user.ini:/usr/local/etc/php/conf.d/user.ini
    depends_on:
      - mysql
      - redis
  nginx:
    image: nginx:alpine
    volumes:
      - .:/var/www/html
      - .docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    ports:
      - '8000:80'
  redis:
    image: redis:alpine
  mysql:
    build: .docker/mysql
    volumes:
      - .docker/mysql/dbdata:/var/lib/mysql
      - .docker/mysql/entrypoint-initdb:/docker-entrypoint-initdb.d
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --innodb-use-native-aio=0
    ports:
      - '33006:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_DATABASE=laravel
  xdebug:
    build:
      context: .docker/php
      target: xdebug
    volumes:
      - .:/var/www/html
      - .docker/php/.user.ini:/usr/local/etc/php/conf.d/user.ini
      - .docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    environment:
      - PHP_IDE_CONFIG=serverName=localhost
      - XDEBUG_CONFIG=remote_host=192.168.0.5 remote_port=9000
    entrypoint: dockerize -wait tcp://mysql:3306 -timeout 40s php-fpm
    depends_on:
      - mysql
      - redis
